### ISSUE TITLE
bug 1.1.1 -> 1.2.0 : Attempt to get attribute from null value when AzFW tag undefined

### ISSUE THREAD

**Issue by cbezenco** [Azure/terraform-azurerm-hubnetworking#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.9.5

### Module Version

1.2.0

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

AzFW

### Terraform Configuration Files

```hcl
PS C:\git\alz-dev> terraform version
Terraform v1.9.5
on windows_amd64
+ provider registry.terraform.io/azure/azapi v1.14.0
+ provider registry.terraform.io/azure/modtm v0.3.2
+ provider registry.terraform.io/hashicorp/azurerm v3.114.0
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/hashicorp/time v0.12.0
PS C:\git\alz-dev> terraform init -reconfigure
Initializing the backend...

Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing modules...
Initializing provider plugins...
- Reusing previous version of azure/azapi from the dependency lock file
- Reusing previous version of hashicorp/time from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Reusing previous version of azure/modtm from the dependency lock file
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v3.114.0
- Using previously-installed azure/azapi v1.14.0
- Using previously-installed hashicorp/time v0.12.0
- Using previously-installed hashicorp/random v3.6.2
- Using previously-installed azure/modtm v0.3.2
```

### tfvars variables values

```hcl
Not sure it helps, you would need the full myalz module... 

configuration_file_path         = "config-hub-spoke-dev.yaml"
default_location                = "uksouth"
default_postfix                 = "lz"
root_parent_management_group_id = "alz"
subscription_id_connectivity    = "xxx"
subscription_id_identity        = "xxx"
subscription_id_management      = "xxx"
env                             = "dev"
myalz_tags = {
  "deployedby" = "myalz"
  "env"        = "dev"
}
```

### Debug Output/Panic Output

```shell
Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
```

### Expected Behaviour

Initial deployment of ALZ using hubnetworking 1.1.1 module works fine but since I upgraded from hubnetworking 1.1.1 to 1.2.0 a few days back, I am seeing those errors when doing terraform apply.  

### Actual Behaviour

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # module.myalz-dev.module.enterprise_scale[0].azurerm_resource_group.management["/subscriptions/93650df8-26c3-4ea5-b32c-aa272175569d/resourceGroups/rg-dev-mgmt"] will be updated in-place
  ~ resource "azurerm_resource_group" "management" {
        id         = "/subscriptions/93650df8-26c3-4ea5-b32c-aa272175569d/resourceGroups/rg-dev-mgmt"
        name       = "rg-dev-mgmt"
      ~ tags       = {
          ~ "deployedBy" = "myalz" -> "terraform/azure/caf-enterprise-scale"
          + "deployedby" = "myalz"
            "env"        = "dev"
        }
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│
│   with module.myalz-dev.module.hubnetworking[0].module.hub_virtual_networks["swedencentral"].azurerm_subnet.subnet["SNetPrivateEndpoint"],
│   on .terraform\modules\myalz-dev.hubnetworking.hub_virtual_networks\main.tf line 35, in resource "azurerm_subnet" "subnet":
│   35:   private_endpoint_network_policies_enabled     = var.subnets[each.value].private_endpoint_network_policies_enabled
│
│ `private_endpoint_network_policies_enabled` will be removed in favour of the property `private_endpoint_network_policies` in version 4.0 of the AzureRM Provider
│
│ (and 16 more similar warnings elsewhere)
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵

### Steps to Reproduce

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform planned the following actions, but then encountered a problem:

  # module.myalz-dev.module.enterprise_scale[0].azurerm_resource_group.management["/subscriptions/93650df8-26c3-4ea5-b32c-aa272175569d/resourceGroups/rg-dev-mgmt"] will be updated in-place
  ~ resource "azurerm_resource_group" "management" {
        id         = "/subscriptions/93650df8-26c3-4ea5-b32c-aa272175569d/resourceGroups/rg-dev-mgmt"
        name       = "rg-dev-mgmt"
      ~ tags       = {
          ~ "deployedBy" = "myalz" -> "terraform/azure/caf-enterprise-scale"
          + "deployedby" = "myalz"
            "env"        = "dev"
        }
        # (2 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
╷
│ Warning: Argument is deprecated
│
│   with module.myalz-dev.module.hubnetworking[0].module.hub_virtual_networks["swedencentral"].azurerm_subnet.subnet["SNetPrivateEndpoint"],
│   on .terraform\modules\myalz-dev.hubnetworking.hub_virtual_networks\main.tf line 35, in resource "azurerm_subnet" "subnet":
│   35:   private_endpoint_network_policies_enabled     = var.subnets[each.value].private_endpoint_network_policies_enabled
│
│ `private_endpoint_network_policies_enabled` will be removed in favour of the property `private_endpoint_network_policies` in version 4.0 of the AzureRM Provider
│
│ (and 16 more similar warnings elsewhere)
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 37, in locals:
│   37:       tags                = vnet.firewall.default_ip_configuration.tags
│     ├────────────────
│     │ vnet.firewall.default_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵
╷
│ Error: Attempt to get attribute from null value
│
│   on .terraform\modules\myalz-dev.hubnetworking\locals.tf line 48, in locals:
│   48:       tags                = v.firewall.management_ip_configuration.tags
│     ├────────────────
│     │ v.firewall.management_ip_configuration is null
│
│ This value is null, so it does not have any attributes.
╵

### Important Factoids

The error does not show up when downgrading hubnetworking module to 1.1.1.

### References

NA

**Comment by matt-FFFFFF** [comment]
Closed in #84 thank you
